# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fNzcZLaCApAxYSdlZqIMGmR3rAEAkZgk
"""

import requests

API = "f37812b9f0feb8f0b52b0a1659441ff8"
x = "Manchester"
y = f"https://api.openweathermap.org/data/2.5/weather?q={cidade}&appid={api_key}&lang=pt_br"

xx = requests.get(y)

yy_dic = xx.json()

dd = yy_dic['weather'][0]['description']

tt = (yy_dic['main']['temp']-273)

print(f"-Em Manchester a temperatura nesse momento é: {tt}ºC")
print(f"-Em Manchester o ceu está dessa forma: {dd}")

